services:
  client:
    build: ./client
    ports:
      - 4200:4200
  api:
    build: 
      context: ./nodeapi
    ports:
      - 5000:5000
    depends_on:
      - emongo
  webapi:
    build: 
      context: ./javaapi
    ports:
      - 9000:9000
    restart: on-failure
    depends_on:
      - emartdb
  emongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - 27017:27017
  emartdb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - api
      - webapi
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    
